package app.habit.service.gpt.prompt;

public class PromptExample {

    public static final String HABIT_PRE_QUESTION_PROMPT = "SITUATION\n"
            + "Many people strive to develop new habits, but often struggle to track their progress and ensure their efforts align with broader goals.\n"
            + "Recognizing and addressing these issues is critical to successful habit formation.\n"
            + "\n"
            + "TASK\n"
            + "Create a structured series of questions to evaluate a person's progress in forming new habits.\n"
            + "These questions should address five key perspectives below:\n"
            + "1. General perception and intention\n"
            + "2. Goal clarity and planning\n"
            + "3. Initial actions and small steps\n"
            + "4. Consistency and practice\n"
            + "5. Integration of maintenance and lifestyle\n"
            + "\n"
            + "INTENT\n"
            + "The purpose of these questions is to help individuals reflect on their journey toward habit formation, identify areas where they may need to adjust their approach, and commit to incorporating these habits into their lifestyle.\n"
            + "\n"
            + "CONCERNS\n"
            + "One potential problem is that the questions are comprehensive yet simple enough for individuals to understand and apply them to their own context.\n"
            + "It is also important to encourage honest self-reflection without becoming discouraged.\n"
            + "\n"
            + "CALIBRATION\n"
            + "You must reply me in JSON format.\n"
            + "When providing a response in JSON format, the following information must be observed. That's the most important part.\n"
            + "1. Be sure to follow the JSON structure below.\n"
            + "In particular, the object structure below and the fact that one question must be asked from each of the five perspectives must be perfectly observed.\n"
            + "2. The values \u200B\u200Bof key, questionKey, and question may be different.\n"
            + "In particular, it would be nice if questions were asked more specifically in the example below to encourage self-reflection in users!\n"
            + "3. When responding to me, translate the English response into Korean.\n"
            + "4. You will probably put the response in the below json format in the String type content field,\n"
            + "This is very important at this time, and I would like you to provide the following structure in the same Json structure, not the String type\n"
            + "5. If you think the response will exceed 4096 tokens while re-watching the response, process the response and deliver it to me so that it doesn't exceed 4096 tokens. "
            + "Of course, the final response to me should be in the same format as previously mentioned\n"
            + "A very easy way to follow the above method is to remove the outermost commas of the content field of the message object of the response you will create.\n"
            + "\n"
            + "JSON structure example\n"
            + "\n"
            + "[\n"
            + "{\n"
            + "\"key\" : \"1\",\n"
            + "\"subject\" : \"General perception and intention\",\n"
            + "\"questionRs\" : {\n"
            + "\"questionKey\" : \"1\",\n"
            + "\"question\" : \"What habits are you currently trying to develop, and why do you think they are important?\"\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"key\": \"2\",\n"
            + "\"subject\" : \"Goal clarity and planning\",\n"
            + "\"questionRs\" : {\n"
            + "\"questionKey\" : \"2\",\n"
            + "\"question\" : \"Have you set specific goals related to this habit? What steps have you planned to achieve these goals?\"\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"key\" : \"3\",\n"
            + "\"subject\" : \"Initial actions and small steps\",\n"
            + "\"questionRs\" : {\n"
            + "\"questionKey\" : \"3\",\n"
            + "\"question\" : \"What is the smallest step you have taken or plan to take to start this habit?\"\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"key\" : \"4\",\n"
            + "\"subject\" : \"Consistency and practice\",\n"
            + "\"questionRs\" : {\n"
            + "\"questionKey\" : \"4\",\n"
            + "\"question\" : \"How consistently have you been able to perform this habit and how do you monitor your progress?\"\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"key\" : \"5\",\n"
            + "\"subject\" : \"Maintenance and lifestyle integration\",\n"
            + "\"questionRs\" : {\n"
            + "\"questionKey\" : \"5\",\n"
            + "\"question\" : \"Have you ever had trouble maintaining these habits over time? How have you dealt with them?\"\n"
            + "}\n"
            + "}\n"
            + "]";
}
